import type { Profile } from "@/lib/profile-schema";

/**
 * 8 seed sample profiles for development + sub-plan testing.
 * 4 male + 4 female; covers all 4 Torah levels; covers both polygyny
 * stances; varies country/ethnicity. Each profile passes
 * `computeCompleteness().discoverEligible` (all 6 minimum fields).
 */
export const SAMPLE_PROFILES: ReadonlyArray<Profile> = [
  {
    firstName: "Daniel",
    age: 32,
    sex: "male",
    country: "BB",
    nationality: "barbadian",
    ethnicities: ["afro-caribbean"],
    languages: ["en"],
    assembly: "torah-observant",
    torahLevel: "experienced",
    shabbat: "friday-sunset-saturday-sunset",
    feastDays: ["passover", "shavuot", "sukkot", "yom-kippur"],
    calendar: "aviv-barley",
    intent: "first-wife",
    polygyny: "supports",
    headCovering: "encouraged",
    tzitzit: "regularly",
    familyViews: ["wants-children", "interested-large-family"],
    livingPreferences: ["rural", "homestead"],
    healthTags: ["non-smoker", "no-alcohol", "natural-health"],
    interests: ["scripture-study", "hebrew-language", "homesteading"],
    personalityTraits: ["leadership-oriented", "disciplined", "calm"],
    relocation: "wants-partner-willing",
    communicationPrefs: ["video-calls", "in-person"],
    verificationTags: ["government-id", "video-selfie"],
    boundaryTags: [],
    bio: "Carpenter, homesteader, learning to live by Torah day-by-day. Looking to build a Torah-keeping household together.",
  },
  {
    firstName: "Esther",
    age: 28,
    sex: "female",
    country: "US",
    nationality: "american",
    ethnicities: ["afro-american"],
    languages: ["en"],
    assembly: "hebrew-israelite",
    torahLevel: "intermediate",
    shabbat: "friday-sunset-saturday-sunset",
    feastDays: ["passover", "trumpets", "yom-kippur", "sukkot"],
    calendar: "observational-new-moon",
    intent: "unmarried-man",
    polygyny: "monogamy-only",
    headCovering: "required",
    familyViews: ["wants-children"],
    livingPreferences: ["urban", "community-living"],
    healthTags: ["non-smoker", "fitness"],
    interests: ["modest-fashion", "music-ministry", "feast-gatherings"],
    personalityTraits: ["nurturing", "intellectual"],
    relocation: "local-only",
    communicationPrefs: ["texting", "in-person"],
    verificationTags: ["government-id"],
    boundaryTags: ["monogamy-only", "no-smokers"],
    bio: "Teacher and worshipper. Looking for a man of Torah who will lead a household.",
  },
  {
    firstName: "Yosef",
    age: 41,
    sex: "male",
    country: "JM",
    nationality: "jamaican",
    ethnicities: ["afro-caribbean"],
    languages: ["en"],
    assembly: "hebrew-israelite",
    torahLevel: "intermediate",
    shabbat: "luni-solar",
    feastDays: ["passover", "shavuot", "trumpets", "yom-kippur", "sukkot"],
    calendar: "luni-solar",
    intent: "additional-wife",
    polygyny: "supports",
    headCovering: "encouraged",
    tzitzit: "occasionally",
    familyViews: ["has-children", "open-to-more"],
    livingPreferences: ["rural"],
    healthTags: ["non-smoker", "moderate-alcohol", "prepper"],
    interests: ["history-research", "prophecy-studies", "ancient-cultures"],
    personalityTraits: ["traditional", "assertive"],
    relocation: "international-open",
    communicationPrefs: ["video-calls", "frequent"],
    verificationTags: ["government-id", "video-selfie", "community-references"],
    boundaryTags: [],
    bio: "Father of three, ten years in the assembly, building toward a Torah-led house.",
  },
  {
    firstName: "Adina",
    age: 24,
    sex: "female",
    country: "IL",
    nationality: "israeli",
    ethnicities: ["middle-eastern"],
    languages: ["en", "he"],
    assembly: "messianic",
    torahLevel: "experienced",
    shabbat: "friday-sunset-saturday-sunset",
    feastDays: ["passover", "shavuot", "trumpets", "yom-kippur", "sukkot", "hanukkah", "purim"],
    calendar: "rabbinic",
    intent: "courtship",
    polygyny: "monogamy-only",
    headCovering: "encouraged",
    familyViews: ["wants-children"],
    livingPreferences: ["urban"],
    healthTags: ["non-smoker", "no-alcohol", "fitness"],
    interests: ["hebrew-language", "paleo-hebrew", "music-ministry", "scripture-study"],
    personalityTraits: ["intellectual", "calm", "humorous"],
    relocation: "international-open",
    communicationPrefs: ["video-calls"],
    verificationTags: ["government-id"],
    boundaryTags: ["monogamy-only", "serious-courtship-only"],
    bio: "Born here, came back to Torah three years ago. Music ministry and scripture study fill my week.",
  },
  {
    firstName: "Caleb",
    age: 36,
    sex: "male",
    country: "ZA",
    nationality: "south-african",
    ethnicities: ["southern-african"],
    languages: ["en"],
    assembly: "independent",
    torahLevel: "intermediate",
    shabbat: "saturday-only",
    feastDays: ["passover", "yom-kippur", "sukkot"],
    calendar: "rabbinic",
    intent: "marriage-only",
    polygyny: "open",
    headCovering: "optional",
    tzitzit: "occasionally",
    familyViews: ["wants-children", "open-blended"],
    livingPreferences: ["rural", "off-grid"],
    healthTags: ["non-smoker", "prepper", "natural-health"],
    interests: ["survival-skills", "farming", "apologetics"],
    personalityTraits: ["reserved", "disciplined"],
    relocation: "wants-partner-willing",
    communicationPrefs: ["slow-paced-courtship"],
    verificationTags: ["government-id"],
    boundaryTags: ["no-long-distance"],
    bio: "Smallholding farmer. Steady. Looking for a partner who values land and quiet.",
  },
  {
    firstName: "Rivka",
    age: 31,
    sex: "female",
    country: "GB",
    nationality: "british",
    ethnicities: ["afro-caribbean", "european", "mixed-heritage"],
    languages: ["en", "fr"],
    assembly: "christian-transitioning",
    torahLevel: "learning",
    shabbat: "friday-sunset-saturday-sunset",
    feastDays: ["passover", "sukkot"],
    calendar: "aviv-barley",
    intent: "open-to-relocation",
    polygyny: "undecided",
    headCovering: "encouraged",
    familyViews: ["wants-children"],
    livingPreferences: ["urban", "open-to-relocation"],
    healthTags: ["non-smoker", "fitness", "herbalist"],
    interests: ["scripture-study", "natural-hair", "modest-fashion", "cooking"],
    personalityTraits: ["adventurous", "extroverted", "nurturing"],
    relocation: "international-open",
    communicationPrefs: ["video-calls", "frequent"],
    verificationTags: ["government-id", "video-selfie"],
    boundaryTags: [],
    bio: "Two years out of the church, two years into Torah. Curious, learning, ready for a partner who's a few steps ahead.",
  },
  {
    firstName: "Ezekiel",
    age: 47,
    sex: "male",
    country: "NG",
    nationality: "nigerian",
    ethnicities: ["west-african"],
    languages: ["en"],
    assembly: "non-denom-torah",
    torahLevel: "experienced",
    shabbat: "friday-sunset-saturday-sunset",
    feastDays: ["passover", "shavuot", "trumpets", "yom-kippur", "sukkot", "hanukkah"],
    calendar: "aviv-barley",
    intent: "additional-wife",
    polygyny: "supports",
    headCovering: "required",
    tzitzit: "regularly",
    familyViews: ["has-children", "interested-large-family"],
    livingPreferences: ["rural", "homestead", "community-living"],
    healthTags: ["non-smoker", "no-alcohol", "natural-health", "herbalist"],
    interests: ["scripture-study", "youth-mentorship", "community-building", "prophecy-studies"],
    personalityTraits: ["leadership-oriented", "traditional", "disciplined", "calm"],
    relocation: "international-open",
    communicationPrefs: ["video-calls", "slow-paced-courtship"],
    verificationTags: ["government-id", "video-selfie", "assembly", "community-references"],
    boundaryTags: [],
    bio: "Husband, father, teacher. Polygyny-practicing 12 years. Open to a sincere co-wife who values family + community.",
  },
  {
    firstName: "Tirzah",
    age: 22,
    sex: "female",
    country: "GH",
    nationality: "ghanaian",
    ethnicities: ["west-african"],
    languages: ["en"],
    assembly: "torah-observant",
    torahLevel: "beginner",
    shabbat: "friday-sunset-saturday-sunset",
    feastDays: ["passover", "sukkot"],
    calendar: "aviv-barley",
    intent: "courtship",
    polygyny: "open",
    headCovering: "encouraged",
    familyViews: ["wants-children"],
    livingPreferences: ["urban", "open-to-relocation"],
    healthTags: ["non-smoker", "no-alcohol"],
    interests: ["music-ministry", "cooking", "youth-mentorship"],
    personalityTraits: ["humorous", "nurturing", "adventurous"],
    relocation: "international-open",
    communicationPrefs: ["video-calls", "frequent"],
    verificationTags: ["government-id"],
    boundaryTags: ["serious-courtship-only"],
    bio: "Recently came into Torah observance. Joyful, growing, looking for a man rooted in his walk.",
  },
];

/** Case-insensitive lookup by firstName. */
export function sampleByName(name: string): Profile | undefined {
  const target = name.toLowerCase();
  return SAMPLE_PROFILES.find(
    (p) => p.firstName?.toLowerCase() === target,
  );
}
